import type { Metadata } from "next";
import "./main.scss";
import Navbar from "./components/Navbar";
import { CategoryProvider } from "./context/CategoryContext";
import { AuthProvider } from "./context/AuthContext";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "EsportCardNepal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </head>
      <body className={`antialiased`}>
        <AuthProvider>
          <CategoryProvider>
            <Navbar />
            {children}
            <Footer />
          </CategoryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
