# Generated by Django 5.1.4 on 2024-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
