# Generated by Django 5.1.4 on 2024-12-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="rechargerequest",
            name="external_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
